### ISSUE TITLE
glpi 10 : misplaced ribbon in modal

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#10269]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10

### Bug description

If a modal is used to add an item, the ribbon is not well positionned

![image](https://user-images.githubusercontent.com/14139801/148233575-31e5e122-66f9-459d-bb41-d3e9d10368cd.png)

In Formcreator, I have this to fix some cases, which is a good start to a fix in the core

```scss
.modal-dialog .card-header {
   // Fix ribbon position
   position: relative;
}
```

To reproduce you can add a itil category from a ticket
