### ISSUE TITLE
CSS - rendering issue in  ticket description if it contains H2 tag

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#2981]
![image](https://user-images.githubusercontent.com/14139801/31602725-3c1b668e-b25e-11e7-9290-000b839ca03e.png)
**header 2** has **float: left ** because **Actions historical** is in H2 HTML tag.

```css
.timeline_history h2 {
   float: left;
}
```
