### ISSUE TITLE
Simcard status is shown pin code column

### ISSUE THREAD

**Issue by SL-Gundam** [glpi-project/glpi#3247]
I added a status to a Simcard item. In Components -> Simcards -> Items, the filled in status is shown in the Status column and in the PIN code column. This only applies when a PIN code has been filled in

[code]   GLPI 9.2.1 (/glpi => C:\inetpub\wwwroot\glpi) Installation mode: TARBALL
--

Operating system: Windows NT MOD-IIS5 6.3 build 9600 (Windows Server 2012 R2 Standard Edition) AMD64 PHP 7.1.3 cgi-fcgi (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, 	com_dotnet, ctype, curl, date, dom, enchant, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, 	libxml, mbstring, mcrypt, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pdo_sqlsrv, pgsql, 	phpdbg_webhelper, readline, session, shmop, soap, sockets, sqlite3, sqlsrv, standard, sysvshm, tidy, tokenizer, wddx, wincache, 	xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="100M" safe_mode="" session.save_handler="files" 	upload_max_filesize="100M"  Software: Microsoft-IIS/8.5 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36 Server Software: mariadb.org binary distribution 	Server Version: 5.5.42-MariaDB-log 	Server SQL Mode:  	Parameters: scheduler@mod-db6/glpi 	Host info: mod-db6 via TCP/IP 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed xmlrpc extension is installed APCu extension is not present C:\inetpub\wwwroot\glpi/config : OK C:\inetpub\wwwroot\glpi/files : OK C:\inetpub\wwwroot\glpi/files/_dumps : OK C:\inetpub\wwwroot\glpi/files/_sessions : OK C:\inetpub\wwwroot\glpi/files/_cron : OK C:\inetpub\wwwroot\glpi/files/_graphs : OK C:\inetpub\wwwroot\glpi/files/_lock : OK C:\inetpub\wwwroot\glpi/files/_plugins : OK C:\inetpub\wwwroot\glpi/files/_tmp : OK C:\inetpub\wwwroot\glpi/files/_cache : OK C:\inetpub\wwwroot\glpi/files/_rss : OK C:\inetpub\wwwroot\glpi/files/_uploads : OK C:\inetpub\wwwroot\glpi/files/_pictures : OK C:\inetpub\wwwroot\glpi/files/_log : OK Web access to files directory is protected : OK

htmLawed version 1.2.4 in (C:\inetpub\wwwroot\glpi\lib\htmlawed) phpCas version 1.3.5 in (C:\inetpub\wwwroot\glpi\vendor\jasig\phpcas\source) PHPMailer version 5.2.26 in (C:\inetpub\wwwroot\glpi\vendor\phpmailer\phpmailer) SimplePie version 1.5.1 in (C:\inetpub\wwwroot\glpi\vendor\simplepie\simplepie\library) TCPDF version 6.2.13 in (C:\inetpub\wwwroot\glpi\vendor\tecnickcom\tcpdf) michelf/php-markdown in (C:\inetpub\wwwroot\glpi\vendor\michelf\php-markdown\Michelf) true/punycode in (C:\inetpub\wwwroot\glpi\vendor\true\punycode\src) iacaml/autolink in (C:\inetpub\wwwroot\glpi\vendor\iamcal\lib_autolink) sabre/vobject in (C:\inetpub\wwwroot\glpi\vendor\sabre\vobject\lib)

Server: 'dc01', Port: '389', BaseDN: 'OU=Gebruikers,DC=so,DC=local', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'so\administrator', Use 		TLS: none

Not active

Way of sending emails: SMTP (anonymous@data01.so.local)

 

behaviors            Name: Behaviours                     Version: 1.5.2      State: Not installed 	fusioninventory      Name: FusionInventory                Version: 9.2+1.0    State: Enabled
[/code]

**Comment by pVesian** [comment]
Hi, I wasn't able to reproduce this. Could you please add screenshots?

**Comment by pVesian** [comment]
@trasher Confirmed on 9.2.1 and 9.2.3.
@SL-Gundam thanks for the screenshots it helped a lot to reproduce the issue.
Technical details to follow

**Comment by pVesian** [comment]
The PIN & PUK data is correctly stored in the database, so this must be coming from one of the HTMLTable* classes. I don't know which one as it's a bowl of wibbly wobbly stuff.
```
mysql> SELECT * FROM glpi_items_devicesimcards \G
*************************** 1. row ***************************
               id: 1
         items_id: 2
         itemtype: Phone
devicesimcards_id: 1
       is_deleted: 0
       is_dynamic: 0
      entities_id: 0
     is_recursive: 0
           serial: NULL
      otherserial: NULL
        states_id: 7
     locations_id: 0
         lines_id: 0
              pin: codepin
             pin2: codepin2
              puk: codepuk
             puk2: codepuk2
             msin: 
1 row in set (0,00 sec)
```
