### ISSUE TITLE
Please help me, how the asset data is centered

### ISSUE THREAD

**Issue by Aiznewong** [glpi-project/glpi#5022]
Hi Guys,
             Please help me, how the asset data is centered, asset data is always displayed on the left, how to center the alignment, need to change the 'styles.css' file? If you need to make changes.
![1](https://user-images.githubusercontent.com/45619168/49497840-5473cb80-f8a4-11e8-8b7f-18fff84f414f.png)

**Comment by trasher** [comment]
You mean you want to align on left table headers?

See styles.css , line 992 (GLPI 9.3.3):
```css
.tab_cadre th, .tab_cadre_fixe th, .tab_cadre_fixehov th, .tab_cadrehov th, h2.header {
   /*[...]*/
   text-align: center;
   /*[...]*/
}
```

Please keep ticket for bugs, see website for all possible channels you can use for questions.
